# Generated by Selenium IDE
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestUpdateDeploy():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_updateDeploy(self):
    self.driver.get("https://whm.harriswebworks.com:2083/cpsess1073982240/frontend/paper_lantern/version_control/index.html")
    self.driver.set_window_size(865, 664)
    element = self.driver.find_element(By.ID, "imgLogo")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.execute_script("window.scrollTo(0,0)")
    self.driver.find_element(By.LINK_TEXT, "Pull or Deploy").click()
    self.driver.find_element(By.CSS_SELECTOR, "#btnUpdateFromRemote > .button-label > span").click()
    self.driver.find_element(By.CSS_SELECTOR, "#btnDeployRepository > .button-label > span").click()
  
